/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.max.tester.gui.timetable;

import java.awt.Color;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import me.max.tester.managers.system.SystemExit;

/**
 *
 * @author Mc170171
 */
public class Fronter extends javax.swing.JFrame {

    // constants
    
    //
    
    
    // methods
    
    protected HashMap<Integer, String> getTimeTableMap() {
        
        HashMap<Integer, String> map = new HashMap<>();
        
        map.put(1, "Computer Science;11:40+Maths;15:10"); //mon
        map.put(2, "Computer Science;09:00+Computer Science;10:10+Economics;11:40+Tutor;12:45"); //tue
        map.put(3, "Computer Science;11:40+Maths;15:10"); //wed
        map.put(4, "Computer Science;11:40+Maths;15:10"); //thu
        map.put(5, "Computer Science;11:40+Maths;15:10"); //fri
     
        return map;
    }
    
    
    
    /**
     * Creates new form Fronter
     */
    public Fronter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        pBar = new javax.swing.JProgressBar();
        pBarFriday = new javax.swing.JLabel();
        pBarMonday = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        pWordField = new javax.swing.JPasswordField();
        banner = new javax.swing.JLabel();
        pWordPrompt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Agency FB", 1, 56)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 0));
        titleLabel.setText("Timetable - Max Carter [MC170171]");

        exitButton.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 51, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        pBarFriday.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        pBarFriday.setForeground(new java.awt.Color(255, 51, 0));
        pBarFriday.setText("Friday!");

        pBarMonday.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        pBarMonday.setForeground(new java.awt.Color(255, 51, 0));
        pBarMonday.setText("Monday!");

        updateButton.setFont(new java.awt.Font("Agency FB", 3, 36)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 51, 51));
        updateButton.setText("Update!");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        pWordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        pWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWordFieldActionPerformed(evt);
            }
        });

        banner.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/max/tester/gui/timetable/resources/background/rcbanner.PNG"))); // NOI18N
        banner.setText("picHold");

        pWordPrompt.setFont(new java.awt.Font("Agency FB", 2, 18)); // NOI18N
        pWordPrompt.setText("Enter password to continue!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 1419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(pBarMonday)
                        .addGap(18, 18, 18)
                        .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pBarFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pWordPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(pWordField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pBarMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pBarFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pWordPrompt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        SystemExit exit = new SystemExit();
        exit.exitProgram();
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void pWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Update Button
        
        char[] pw = pWordField.getPassword();
        char[] correct = new char[] {'y', 'e', 's'};
        
        if (Arrays.equals(pw, correct)) {
            pWordField.setVisible(false);
            pWordPrompt.setVisible(false);
            updateButton.setVisible(false);
        } else {
            pWordPrompt.setText("Wrong password!");
            pWordPrompt.setForeground(Color.red);
            pWordField.requestFocusInWindow();
        }
        
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fronter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton exitButton;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JLabel pBarFriday;
    private javax.swing.JLabel pBarMonday;
    private javax.swing.JPasswordField pWordField;
    private javax.swing.JLabel pWordPrompt;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
